apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: storetrack
  namespace: storetrack
  labels:
    app.kubernetes.io/name: storetrack
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: storetrack
